### ISSUE TITLE
Error when I run roslaunch tello_driver

### ISSUE THREAD

**Issue by huberth16** [anqixu/tello_driver#10]
Hi guys, I new on ROS and Tello, I followed up the instructions but when I try to run "roslaunch tello_driver/launch/tello_node.launch" I get the following:

> huberth@huberth-PL62-7RC:~$ roslaunch tello_driver/launch/tello_node.launch
> ... logging to /home/huberth/.ros/log/35bfda92-263b-11ea-8165-4ccc6ae26d64/roslaunch-huberth-PL62-7RC-9145.log
> Checking log directory for disk usage. This may take awhile.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://huberth-PL62-7RC:43971/
> 
> SUMMARY
> ========
> 
> PARAMETERS
>  * /rosdistro: kinetic
>  * /rosversion: 1.12.14
>  * /tello/tello/connect_timeout_sec: 10.0
>  * /tello/tello/local_cmd_client_port: 8890
>  * /tello/tello/local_vid_server_port: 6038
>  * /tello/tello/stream_h264_video: False
>  * /tello/tello/tello_cmd_server_port: 8889
>  * /tello/tello/tello_ip: 192.168.10.1
> 
> NODES
>   /tello/
>     image_compressed (image_transport/republish)
>     tello (tello_driver/tello_driver_node.py)
> 
> ROS_MASTER_URI=http://localhost:11311
> 
> process[tello/tello-1]: started with pid [9163]
> process[tello/image_compressed-2]: started with pid [9164]
> Traceback (most recent call last):
>   File "/opt/ros/kinetic/share/tello_driver/tello_driver_node.py", line 9, in <module>
>     from h264_image_transport.msg import H264Packet
> ImportError: No module named h264_image_transport.msg
> [tello/tello-1] process has died [pid 9163, exit code 1, cmd /opt/ros/kinetic/share/tello_driver/tello_driver_node.py __name:=tello __log:=/home/huberth/.ros/log/35bfda92-263b-11ea-8165-4ccc6ae26d64/tello-tello-1.log].
> log file: /home/huberth/.ros/log/35bfda92-263b-11ea-8165-4ccc6ae26d64/tello-tello-1*.log

So, I have looked at different issues in some forum but I couldn't find the solution, I think it has to be related to the video camera, but I'm sure.

Please help me.

**Comment by anqixu** [comment]
It looks like you have not downloaded + compiled h264_image_transport package. Check out the instructions [here](https://github.com/anqixu/tello_driver#installation).

**Comment by huberth16** [comment]
> It looks like you have not downloaded + compiled h264_image_transport package. Check out the instructions [here](https://github.com/anqixu/tello_driver#installation).

Thank you for your answer. I have followed all the instructions. I had some problem to install rosdep install h264_image_transport  but in the end I manage by copying the file in the directory he asked me. 

However, I still get the same problem, look at this screenshot:
![tello1](https://user-images.githubusercontent.com/59199158/71444191-2152e300-2718-11ea-9635-76e5100a1f67.png)

In the picture you can see the installation was succesfull. But still get the same problem. I also have checked the files H264Packet.msg and it is in this adress:

> root@huberth-PL62-7RC:/opt/ros/kinetic/share/image_transport# find /opt/ros/ -name H264Packet.msg
/opt/ros/kinetic/share/h264_image_transport/msg/H264Packet.msg
> /opt/ros/kinetic/share/ros/h264_image_transport/msg/H264Packet.msg

is it in the right place?
I also see the log file and said this:

> [rospy.client][INFO] 2019-12-25 12:12:19,264: init_node, name[/tello/tello_driver_node], pid[4907]
[xmlrpc][INFO] 2019-12-25 12:12:19,264: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-12-25 12:12:19,265: Started XML-RPC server [http://huberth-PL62-7RC:35635/]
[rospy.init][INFO] 2019-12-25 12:12:19,265: ROS Slave URI: [http://huberth-PL62-7RC:35635/]
[rospy.impl.masterslave][INFO] 2019-12-25 12:12:19,265: _ready: http://huberth-PL62-7RC:35635/
[xmlrpc][INFO] 2019-12-25 12:12:19,265: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-12-25 12:12:19,266: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-12-25 12:12:19,365: registered with master
[rospy.rosout][INFO] 2019-12-25 12:12:19,365: initializing /rosout core topic
[rospy.rosout][INFO] 2019-12-25 12:12:19,369: connected to core topic /rosout
[rospy.simtime][INFO] 2019-12-25 12:12:19,371: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.core][INFO] 2019-12-25 12:12:19,385: signal_shutdown [atexit]
[rospy.impl.masterslave][INFO] 2019-12-25 12:12:19,388: 
> atexit

This is all the information I can find.

Please help me

In advance thank you for your help, your future reply is important for me. It is a wonderful project.
