### ISSUE TITLE
No module named av

### ISSUE THREAD

**Issue by guiaugustoga987** [anqixu/tello_driver#13]
Hello,

I'm using Ubuntu 18.04 / Python 2.7.17 / Installed Pyav through (pip install av==0.5.2) / ROS Melodic.

When I try to launch tello_node.launch I'm still getting the error : no module named av.

![Captura de tela de 2021-06-18 02-46-34](https://user-images.githubusercontent.com/56890056/122513844-5b393880-cfe1-11eb-8e75-87a5a16b9de5.png)

Does someone have a workaround for this issue ?

Thanks !

EDIT : It seems like the pyAv is installed on python 3.6 folder. I have no idea how to install it on python 2.7 folder.

![](https://user-images.githubusercontent.com/56890056/122523278-3a76e000-cfed-11eb-8a71-5e02e5114ed0.png)

Any help is appreciated.

**Comment by guiaugustoga987** [comment]
It seems like the pyAv is installed on python 3.6 folder. I have no idea how to install it on python 2.7 folder. 

![Captura de tela de 2021-06-18 04-25-07](https://user-images.githubusercontent.com/56890056/122523278-3a76e000-cfed-11eb-8a71-5e02e5114ed0.png)

Any help is appreciated.

**Comment by anqixu** [comment]
Source ROS' setup.bash, then confirm that `python` runs Python 2.7 (or maybe your system needs to run `python2`). Then run `python -m pip install av` (=<VERSION> if needed)

**Comment by apambalik1337** [comment]
> python -m pip install av

thanks
