### ISSUE TITLE
/tello/image_raw/compressed not sending anything

### ISSUE THREAD

**Issue by MarcoDotIO** [anqixu/tello_driver#18]
Hello,

I've been trying to get a compressed image message sent from the drone, and I cannot seem to have the topic /tello/image_raw/compressed publish anything. /tello/image_raw/h264 does publish the stream however; so how can I get the compressed image to publish the compressed image messages? Using ROS Melodic with everything else being up to date.

**Comment by anqixu** [comment]
Try using [image_view's republish node](http://wiki.ros.org/image_transport)
`$ rosrun image_transport republish [in_transport] in:=<in_base_topic> [out_transport] out:=<out_base_topic>`

**Comment by MarcoDotIO** [comment]
> Try using [image_view's republish node](http://wiki.ros.org/image_transport) `$ rosrun image_transport republish [in_transport] in:=<in_base_topic> [out_transport] out:=<out_base_topic>`

Hello there,

I tried the following command:
`rosrun image_transport republish h264 in:=/tello/image_raw/h264 out:=/tello/image_raw/compressed_transport`

And got the following as the output:
`[ WARN] [1639063394.343590832]: [image_transport] It looks like you are trying to subscribe directly to a transport-specific image topic '/tello/image_raw/h264', in which case you will likely get a connection error. Try subscribing to the base topic '/tello/image_raw' instead with parameter ~image_transport set to 'h264' (on the command line, _image_transport:=h264). See http://ros.org/wiki/image_transport for details.`

Can you help me out further with this issue? Maybe provide a node command that properly fits this case?

**Comment by MarcoDotIO** [comment]
Okay I found the solution to my issue, in the launch/tello_node.launch file, change this following line:
`<node pkg="image_transport" name="image_compressed" type="republish" args="raw in:=image_raw compressed out:=image_raw" />`

to this:
`<node pkg="image_transport" name="image_compressed" type="republish" args="h264 in:=image_raw compressed out:=image_raw" />`

That fixed my issue of the compressed image topic being in the incorrect format. I'm closing this issue now, though one last issue for the devs here; when using the above fix, I'm getting an error like this:
`[ERROR] [*n seconds since wake*]: Cannot send a packet to decoder`

Now this doesn't affect the performance, just that it might raise some issues in the future for anyone else. So please reopen the issue if the devs end up finding the solution, or if anyone else is facing issues that link back to this error.

**Comment by zoldaten** [comment]
@MarcoDotIO hi !
are there another solution to it ? republish leads to freezes and i cant use ORB_SLAM3 with it. but i have ORB_SLAM2 and tello on ROS2 worked pretty well - https://youtu.be/MaZRohrtnrQ

**Comment by abstract-entity** [comment]
> @MarcoDotIO hi ! are there another solution to it ? republish leads to freezes and i cant use ORB_SLAM3 with it. but i have ORB_SLAM2 and tello on ROS2 worked pretty well - https://youtu.be/MaZRohrtnrQ

Same here, have you found any solution for low perf of republishing ? i got a lot error too: 

```
Cannot send a packet to decoder
```

**Comment by BeenToJupiter** [comment]
> > @MarcoDotIO hi ! are there another solution to it ? republish leads to freezes and i cant use ORB_SLAM3 with it. but i have ORB_SLAM2 and tello on ROS2 worked pretty well - https://youtu.be/MaZRohrtnrQ
> 
> Same here, have you found any solution for low perf of republishing ? i got a lot error too:
> 
> ```
> Cannot send a packet to decoder
> ```

I do get the same error when trying to view the compressed image. I do not have any data on the /tello/image_raw topic. Not sure what is the issue
