### ISSUE TITLE
error to install tello_driver 

### ISSUE THREAD

**Issue by edimoon777** [anqixu/tello_driver#2]
Thank you for your efforts to distribute ros driver for tello.

I got error message when I tried to run   
`rosdep install tello_driver`   

<pre>
jungho@jungho-Inspiron-7577:~/catkin_ws$ rosdep install tello_driver
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
tello_driver: Cannot locate rosdep definition for [h264_image_transport]
</pre>

**Comment by anqixu** [comment]
please follow these instructions:
https://github.com/anqixu/tello_driver#installation

in particular, you are missing the custom h264_image_transport ROS package, which you must git-clone from source.
