### ISSUE TITLE
ROS launch path and tello_driver_node.py

### ISSUE THREAD

**Issue by edimoon777** [anqixu/tello_driver#3]
I got these message below, as following your instruction.
(Most of errors happened because of PyAV package, and I solved that through installation from source.)

Do you know how to fix error as below?
It seems that the path should be fixed. [tello_driver/tello_driver] 
I'm not familiar with ROS yet.
Please help me.

Error message
---------------------------------------------
started core service [/rosout]
ERROR: cannot launch node of type [tello_driver/tello_driver_node.py]: tello_driver
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/opt/ros/kinetic/share

Full message
---------------------------------------------------------------------------
jungho@jungho-Inspiron-7577:~/catkin_ws/src$ roslaunch tello_driver/launch/tello_node.launch
... logging to /home/jungho/.ros/log/a8149400-db84-11e8-a3f0-e470b8dab7c7/roslaunch-jungho-Inspiron-7577-4928.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://jungho-Inspiron-7577:40637/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /tello/tello/connect_timeout_sec: 10.0
 * /tello/tello/local_cmd_client_port: 8890
 * /tello/tello/local_vid_server_port: 6038
 * /tello/tello/stream_h264_video: False
 * /tello/tello/tello_cmd_server_port: 8889
 * /tello/tello/tello_ip: 192.168.10.1

NODES
  /tello/
    image_compressed (image_transport/republish)
    tello (tello_driver/tello_driver_node.py)

auto-starting new master
process[master]: started with pid [4938]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to a8149400-db84-11e8-a3f0-e470b8dab7c7
process[rosout-1]: started with pid [4951]
started core service [/rosout]
ERROR: cannot launch node of type [tello_driver/tello_driver_node.py]: tello_driver
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/opt/ros/kinetic/share
process[tello/image_compressed-3]: started with pid [4960]

**Comment by anqixu** [comment]
you need to first:
`source ~/catkin_ws/devel/setup.bash`, which will overlay your catkin workspace (ws) over the default ROS install. Best if you add this to your ~/.bashrc.

See last part of step 2 of following tutorial, beginning with "If you just installed ROS from apt on Ubuntu...":
http://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment
