### ISSUE TITLE
Image with noise and slow

### ISSUE THREAD

**Issue by paul218** [anqixu/tello_driver#6]
hello 

hello , first congratulate you for your work done in the library of ros for drone tello, I'm doing a project with the drone tello, but when capturing the image comes out distorted (green pixel noise) and with delay, maybe you could help me How could I improve this inconvenience since I want to perform image processing in ros with the video obtained from the drone. For your help I give you my thanks

**Comment by anqixu** [comment]
When I've seen this symptom in the past, it was likely due to poor wifi signal. Move the drone closer to the wifi antenna, get a larger antenna, and/or try a wifi repeater. Good luck.
